version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  nodejs:
    build: .
    container_name: my-nodejs-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  app-network:
    driver: bridge
